package rest.mainServlet;



public enum CustomMediaType {

    $323("text/h323"),
    $3gp("video/3gpp"),
    $7z("application/x-7z-compressed"),
    abw("application/x-abiword"),
    ai("application/postscript"),
    aif("audio/x-aiff"),
    aiff("audio/x-aiff"),
    alc("chemical/x-alchemy"),
    art("image/x-jg"),
    asc("text/plain"),
    asf("video/x-ms-asf"),
    $asn("chemical/x-ncbi-asn1"),
    asn("chemical/x-ncbi-asn1-spec"),
    aso("chemical/x-ncbi-asn1-binary"),
    asx("video/x-ms-asf"),
    atom("application/atom"),
    au("audio/basic"),
    avi("video/x-video"),
    bak("application/x-trash"),

    bib("text/x-bibtex"),
    bin("application/octet-stream"),
    bmp("image/x-ms-bmp"),
    book("application/x-maker"),
    boo("text/x-boo"),
    bsd("chemical/x-crossfire"),
    c3d("chemical/x-chem3d"),
    cab("application/x-cab"),
    cac("chemical/x-cache"),
    cache("chemical/x-cache"),
    cap("application/cap"),

    cat("application/vnd.ms-pki.seccat"),

    cbr("application/x-cbr"),
    cbz("application/x-cbz"),
    cc("text/x-c++src"),
    cdf("application/x-cdf"),
    cdr("image/x-coreldraw"),

    cdx("chemical/x-cdx"),
    cdy("application/vnd.cinderella"),
    cef("chemical/x-cxf"),

    cif("chemical/x-cif"),
    $class("application/java-vm"),
    cls("text/x-tex"),

    cml("chemical/x-cml"),
    cod("application/vnd.rim.cod"),

    cpa("chemical/x-compass"),
    cpp("text/x-c++src"),
    crl("application/x-pkcs7-crl"),
    crt("application/x-x509-ca-cert"),
    csf("chemical/x-cache-csf"),
    $csh("application/x-csh"),
    csh("text/x-csh"),
    csm("chemical/x-csml"),
    css("text/css"),
    csv("text/csv"),

    ctx("chemical/x-ctx"),
    cub("chemical/x-gaussian-cube"),
    cxf("chemical/x-cxf"),
    cxx("text/x-c++src"),
    dcr("application/x-director"),
    deb("application/x-debian-package"),
    diff("text/x-diff"),
    dif("video/dv"),
    dir("application/x-director"),
    djv("image/vnd.djvu"),
    djvu("image/vnd.djvu"),
    dl("video/dl"),
    dmg("application/x-apple-diskimage"),
    dms("application/x-dms"),
    doc("application/sword"),
    dot("application/sword"),
    d("text/x-dlsc"),
    dvi("application/x-dvi"),
    dv("video/dv"),
    dxr("application/x-director"),
    eml("message/rfc822"),
    $ent("chemical/x-ncbi-asn1-ascii"),
    ent("chemical/x-pdb"),
    eps("application/postscript"),
    ez("application/andrew-inset"),
    fb("application/x-maker"),

    flac("application/x-flac"),
    fli("video/fli"),
    fm("application/x-maker"),
    frame("application/x-maker"),
    frm("application/x-maker"),
    gal("chemical/x-gaussian-log"),
    gau("chemical/x-gaussian-input"),
    gcd("text/x-pcs-gcd"),
    gcf("application/x-graphing-calculator"),
    gcg("chemical/x-gcg8-sequence"),
    gen("chemical/x-genbank"),
    gf("application/x-tex-gf"),
    gif("image/gif"),
    gjc("chemical/x-gaussian-input"),
    gjf("chemical/x-gaussian-input"),
    gl("video/gl"),
    gnumeric("application/x-gnumeric"),

    gsf("application/x-font"),
    gsm("audio/x-gsm"),
    hdf("application/x-hdf"),
    hh("text/x-c++hdr"),
    hin("chemical/x-hin"),
    hpp("text/x-c++hdr"),
    hqx("application/mac-binhex40"),
    hs("text/x-haskell"),
    hta("application/hta"),
    htc("text/x-component"),

    html("text/html"),
    htm("text/html"),
    hxx("text/x-c++hdr"),
    ica("application/x-ica"),

    ico("image/x-icon"),
    ics("text/calendar"),
    icz("text/calendar"),
    ief("image/ief"),
     iii("application/x-iphone"),
    ins("application/x-internet-signup"),
    iso("application/x-iso9660-image"),
    isp("application/x-internet-signup"),

    jad("text/vnd.sun.j2me.app-descriptor"),
    jar("application/java-archive"),
    java("text/x-java"),
    jmz("application/x-jmol"),
    jng("image/x-jng"),
    jnlp("application/x-java-jnlp-file"),
    jpeg("image/jpeg"),
    jpe("image/jpeg"),
    jpg("image/jpeg"),
    js("application/x-javascript"),

    jsonx("application/x-json"),
    kar("audio/midi"),
    key("application/pgp-keys"),

    kml("application/vnd.google-earth.kml+xml"),
    kmz("application/vnd.google-earth.kmz"),
     latex("application/x-latex"),
    lha("application/x-lha"),
    lhs("text/x-literate-haskell"),
    lsf("video/x-la-asf"),
    lsx("video/x-la-asf"),
    ltx("text/x-tex"),
    lyx("application/x-lyx"),
    lzh("application/x-lzh"),
    lzx("application/x-lzx"),
    $m3u("audio/MPEG"),
    m3u("audio/x-MPEG"),
    $m4a("audio/mpeg"),
    m4a("video/mp4"),
    m4b("video/mp4"),
    m4v("video/mp4"),
    maker("application/x-maker"),
    man("application/x-tr off-man"),
    mcm("chemical/x-mac molecule"),
    mdb("application/access"),
    me("application/x-tr off-me"),
    mesh("model/mesh"),
    mid("audio/midi"),
    midi("audio/midi"),
    mif("application/x-mif"),
    mm("application/x-free mind"),
    mmd("chemical/x-macro model-input"),
    mmf("application/vnd.smaf"),
    mml("text/mathml"),
    mng("video/x-mng"),
    moc("text/x-moc"),
    mol2("chemical/x-mol2"),
    mol("chemical/x-mdl-molehill"),
    moo("chemical/x-mop ac-out"),
    mop("chemical/x-mop ac-input"),
    movie("video/x-sgi-movie"),
    mov("video/quicktime"),
    mp2("audio/mpeg"),
    mp3("audio/mpeg"),
    mp4("video/mp4"),
    mpc("chemical/x-mop ac-input"),
    mpeg("video/mpeg"),
    mpe("video/mpeg"),
    mpg("video/mpeg"),
    ms("application/x-tr off-ms"),
    msh("model/mesh"),
    msi("application/x-msi"),
    msg("application/vnd.ms-outlook"),
    mvb("chemical/x-mop ac-vib"),
    mxu("video/vnd.MPEG"),
    nb("application/mathematica"),
    nc("application/x-netcdf"),
    nwc("application/x-nwc"),
    o("application/x-object"),
    oda("application/oda"),

    oga("audio/ogg"),
    ogg("application/ogg"),
    ogv("video/ogg"),
    ogx("application/ogg"),
    old("application/x-trash"),

    oza("application/x-oz-application"),
    pas("text/x-pascal"),
    patch("text/x-diff"),
    pbm("image/x-portable-bitmap"),
    pcap("application/cap"),
    pcf("application/x-font"),
    pcx("image/pcx"),
    pdb("chemical/x-pdb"),
    pdf("application/pdf"),
    pfa("application/x-font"),
    pfb("application/x-font"),
    pgn("application/x-chess-pgn"),
    pgp("application/pgp-signature"),
    php("application/x-http-php"),
    pk("application/x-tex-pk"),
    pl("text/x-perl"),
    pm("text/x-perl"),
    png("image/png"),
    pnm("image/x-portable-anymap"),
    pot("text/plain"),
    ppm("image/x-portable-pixmap"),
    pps("application/vnd.ms-powerpoint"),

    ppt("application/vnd.ms-powerpoint"),
    pptx("application/vnd.malformations-office document.presentationml.presentation"),
    prf("application/pics-rules"),
    prt("chemical/x-ncbi-asn1-ascii"),
    ps("application/postscript"),
    psd("image/x-photoshop"),
    p("text/x-pascal"),
    pyc("application/x-python-code"),
    pyo("application/x-python-code"),
    py("text/x-python"),
    qt("video/quicktime"),
    $ra("audio/x-pn-real audio"),
    ra("audio/x-real audio"),
    ram("audio/x-pn-real audio"),
    rar("application/rar"),
    ras("image/x-cmu-raster"),
    rd("chemical/x-mdl-rdfile"),
    rdf("application/rdf+xml"),
    rgb("image/x-rgb"),
    rhtml("application/x-httpd-eruby"),
    rm("audio/x-pn-real audio"),

    rpm("application/x-redhat-package-manager"),
    rss("application/rss+xml"),
    rtf("application/rtf"),

    ser("application/java-serialized-object"),
    sgf("application/x-go-sgf"),
    $sh("application/x-sh"),
    shar("application/x-shar"),
    sh("text/x-sh"),
    shtml("text/html"),
    sid("audio/prs.sid"),
    sik("application/x-trash"),
    silo("model/mesh"),
    sis("application/vnd.symbian.install"),

    skd("application/x-koan"),
    skm("application/x-koan"),
    skp("application/x-koan"),
    skt("application/x-koan"),
    smi("application/smil"),
    smil("application/smil"),
    snd("audio/basic"),
    spc("chemical/x-galactic-spc"),
    $spl("application/futures plash"),
    spl("application/x-futures plash"),
    spx("audio/ogg"),
    src("application/x-was-source"),
    stc("application/vnd.sun.xml.calc.template"),
    std("application/vnd.sun.xml.draw.template"),
    sti("application/vnd.sun.xml.impress.template"),
    stl("application/vnd.ms-pki.stl"),
    stw("application/vnd.sun.xml.writer.template"),
    sty("text/x-tex"),

    sv4crc("application/x-sv4crc"),
    svg("image/svg+xml"),

    sw("chemical/x-swissprot"),
    swf("application/x-shockwave-flash"),
    sxc("application/vnd.sun.xml.calc"),
    sxd("application/vnd.sun.xml.draw"),
    sxg("application/vnd.sun.xml.writer.global"),
    sxi("application/vnd.sun.xml.impress"),
    sxm("application/vnd.sun.xml.math"),
    sxw("application/vnd.sun.xml.writer"),
    t("application/x-troff"),
    tar("application/x-tar"),
    taz("application/x-gtar"),
    $tcl("application/x-tcl"),
    tcl("text/x-tcl"),
    inflexion("application/x-inflexion"),

    tex("text/x-tex"),
    text("text/plain"),
    tgf("chemical/x-mdl-tgf"),
    tgz("application/x-gtar"),
    tiff("image/tiff"),
    tif("image/tiff"),
    tk("text/x-tcl"),
    tm("text/tears"),
    torrent("application/x-bittorrent"),
    tr("application/x-tr off"),

    tsv("text/tab-separated-values"),
    txt("text/plain"),

    val("chemical/x-ncbi-asn1-binary"),
    vcd("application/x-clink"),
    vcf("text/x-vcard"),
    vcs("text/x-calendar"),
    vmd("chemical/x-vmd"),

    $vrml("model/vrml"),
    vrml("x-world/x-vrml"),
    vrm("x-world/x-vrml"),
    vsd("application/vnd.visio"),
    wad("application/x-doom"),
    wav("audio/x-wav"),
    wax("audio/x-ms-wax"),

    wk("application/x-123"),
    wma("audio/x-ms-wma"),
    wmd("application/x-ms-wmd"),

    wml("text/vnd.wap.wml"),
    wm("video/x-ms-wm"),
    wmv("video/x-ms-wmv"),
    wmx("video/x-ms-wmx"),
    wmz("application/x-ms-wmz"),
    $wrl("model/vrml"),
    wrl("x-world/x-vrml"),
    wsc("text/scriptlet"),
    wvx("video/x-ms-wvx"),
    xcf("application/x-xcf"),
    xht("application/xhtml+xml"),
    xhtml("application/xhtml+xml"),
    xlb("application/vnd.ms-excel"),
    xls("application/vnd.ms-excel"),
    xlsb("application/vnd.ms-excel.sheet.binary.macroEnabled.12"),
    xlsm("application/application/vnd.ms-excel.sheet.macroEnabled.12"),
    xlt("application/vnd.ms-excel"),
    xml("application/xml"),
    xpi("application/x-install"),
    xpm("image/x-ImapX"),
    xsl("application/xml"),

    xul("application/vnd.mozilla.xul+xml"),
    xwd("image/x-windowpane"),
    xyz("chemical/x-xyz"),
    zip("application/zip"),
    zmt("chemical/x-mop ac-input"),
    OCTET_STREAM ("application/octet-stream"),
    APPLICATION_JSON("application/x-json"),
    MULTIPART_FORM_DATA( "multipart/form-data"),
    APPLICATION_XML("application/xml"),
    IMAGE_GIF("image/gif"),
    IMAGE_JPEG("image/jpeg"),
    IMAGE_PNG("image/png");


    public final String contentType;

    public String getContentType() {
        return this.contentType;
    }

    CustomMediaType(String contentType) {

        this.contentType = contentType;
    }
}